name: Release

on:
  push:
    tags:
      - 'v*' # Run this workflow when a new tag starting with 'v' is pushed

jobs:
  build_linux:
    name: Build Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build (Linux x86_64)
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu

      - name: Package binary
        shell: bash
        run: |
          cd target/x86_64-unknown-linux-gnu/release
          tar -czf amnezia-config-decoder-linux-x86_64.tar.gz amnezia-config-decoder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: amnezia-config-decoder-linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/amnezia-config-decoder-linux-x86_64.tar.gz

  build_windows:
    name: Build Windows x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust and add target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          targets: x86_64-pc-windows-gnu # Add Windows target

      - name: Install cross-compilation tools (mingw-w64 for Windows)
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build (Windows x86_64)
        run: cargo build --verbose --release --target x86_64-pc-windows-gnu

      - name: Package binary
        shell: bash
        run: |
          cd target/x86_64-pc-windows-gnu/release
          zip amnezia-config-decoder-windows-x86_64.zip amnezia-config-decoder.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: amnezia-config-decoder-windows-x86_64
          path: target/x86_64-pc-windows-gnu/release/amnezia-config-decoder-windows-x86_64.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: amnezia-config-decoder-linux-x86_64

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: amnezia-config-decoder-windows-x86_64

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            amnezia-config-decoder-linux-x86_64.tar.gz
            amnezia-config-decoder-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
